# finetuned from u-net model trained on imagenet
# vae fine-tuned on tcga dataset
# Copied of plip_imagenet_finetune.yaml
model:
  base_learning_rate: 2.5e-4
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: caption
    image_size: 64
    channels: 3
    cond_stage_trainable: false #frozen clip encoder
    conditioning_key: crossattn
    monitor: FID
    use_ema: False
    npz_path: FID_full_bravo_1.npz
    ckpt_path: "s3://aiosyn-data-eu-west-1-bucket-ops/models/generation/unet/pathldm/epoch_3-001.ckpt"
    #pretrained unet model v2 (used by Srikar). Should be S3 url
    scheduler_config: # 1000 warmup steps
      target: ldm.lr_scheduler.CosineScheduler
      params:
        lr_warmup_steps: 1000
        lr_max: 1
        lr_start: 1e-6
        total_training_steps: 30000 #Based  on length of trainloader and max_epochs...

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 3
        out_channels: 3
        model_channels: 192
        attention_resolutions: [8, 4, 2]
        num_res_blocks: 2
        channel_mult: [ 1,2,3,5 ]
        num_heads: 1
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 512
        use_fp16: False # Half precision floats, default is float32
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        #ckpt_path: "pretrained/autoencoder/vq-f4/model.ckpt" #The autoencoder vq-f4
        embed_dim: 3
        n_embed: 8192
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder
      params:
        # plip is the pathology clip model
        # plip- model: vinid/plip
        # "openai/clip-vit-base-patch32" # regular clip as used by Srikar
        version: "vinid/plip" # plip
        max_length: 154
data:
  already_downloaded: True # Only applies if running locally. If data is downloaded, you can speed things up.
  dataset_name: dataset-17-bravo-1/patches #the name of the dataset as it is on S3, under patch_datasets
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    num_workers: 12
    wrap: false
    train:
      target: ldm.data.text_cond.thesis_conditioning.KidneyConditional
      params:
        config:
          subsample: False
          root: dataset-17-bravo-1/patches
          csv: dataset-17-bravo-1/patches.csv
          split: train
          flip_p: 0.5
          size: 100000 #Set nr of samples in the data set. If set very large, will default to the size of the full dataset.
          crop_size: 256 # size of the images
    validation:
      target: ldm.data.text_cond.thesis_conditioning.KidneyConditional
      params:
        config:
          root: dataset-17-bravo-1/patches
          csv: dataset-17-bravo-1/patches.csv
          split: validation
          size: 1500
          crop_size: 256

lightning:
  trainer:
    max_epochs: 30
    skip_validation: False # Determines if the validation loop (calculating FID values) is run or not.
    run_name: Conditional run with lr decay, starting at Srikar #Name of the run as used by Neptune
    log_model_checkpoints: False # Tells Neptune to log the model ckpts to Neptune or not. Model ckpts will always be saved to S3
